#ifndef IDX_METADATA_CONFIG_H_
#define IDX_METADATA_CONFIG_H_

#define IDX_FILE_EXTENSION ".idx"
#define IDX_METADATA_FILE_EXTENSION ".xidx"
#define IDX_METADATA_TIME_FORMAT "t%09d"
#define IDX_METADATA_LEVEL_FORMAT "l%04d"
#define IDX_METADATA_MAX_PATH_FILE_LENGTH 1024

#endif